version: "2.12.0"
services:
  
  backend: 
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  
  frontend:
    stdin_open: true 
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /frontend/node_modules