version: "3"
services:
  
  backend: 
    image: blazebd/docker-test:node
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  
  frontend:
    image: blazebd/docker-test:next
    stdin_open: true 
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
  